### ISSUE TITLE
Introductory slides to the hands-on part on software development

### ISSUE THREAD

**Issue by JaroCamphuijsen** [esciencecenter-digital-skills/green-digital-skills#24]
Introduction to software development part of the hands-on workshop including various subtopics and overarching story.

Slides should go in this file: https://github.com/esciencecenter-digital-skills/green-digital-skills/blob/main/modules/software-development-handson/slides_module1.md

**Comment by raar1** [comment]
I think we don't really need this currently. The introduction slides in the hands-on intro module are sufficient.
