### ISSUE TITLE
Add a list of courses people might be interested in

### ISSUE THREAD

**Issue by raar1** [esciencecenter-digital-skills/green-digital-skills#35]
@JaroCamphuijsen @esclapez I think you guys came across a few courses (some masters courses, some green initiative teaching materials etc). Please reply here with any you can remember.

I will add them to the course so we can point people at the correct places to get deeper expertise.

**Comment by esclapez** [comment]
- https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/
