### ISSUE TITLE
Deployed site still old template

### ISSUE THREAD

**Issue by raar1** [esciencecenter-digital-skills/green-digital-skills#4]
The deployed site at <https://esciencecenter-digital-skills.github.io/green-digital-skills/> is still showing the old template material:

![image](https://github.com/esciencecenter-digital-skills/green-digital-skills/assets/2650951/77a45c12-8d3f-4c8a-8384-8b934991d028)

**Comment by JaroCamphuijsen** [comment]
WE can make a release, that will fix it

**Comment by raar1** [comment]
Oh yes, I forgot it was only on release!
