### ISSUE TITLE
Add electricitymaps app to presentation slides

### ISSUE THREAD

**Issue by raar1** [esciencecenter-digital-skills/green-digital-skills#6]
Add it as e.g. an iframe on one of the slides. Also have some screenshots and talking points on the following slide in case the network is bad on the teaching day.

**Comment by raar1** [comment]
It would be good to demo the application a bit during teaching, to make the course a bit more interactive and stop people falling asleep.

**Comment by esclapez** [comment]
Yes ! Maybe asking about where and when to run a workflow, as a small live exercise.

**Comment by raar1** [comment]
This seems to be done.
